# Generated by Django 4.2.2 on 2023-06-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=52)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(blank=True, null=True)),
                ('entrada', models.DateField(auto_now=True)),
                ('saida', models.DateField(auto_now_add=True)),
                ('feriasEntrada', models.DateField()),
                ('feriasSaida', models.DateField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresa')),
            ],
        ),
    ]
