# Generated by Django 4.2.2 on 2023-06-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_empresa_empregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='updatedAt',
        ),
        migrations.AlterField(
            model_name='empregado',
            name='entrada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='saida',
            field=models.DateField(),
        ),
    ]
