# Generated by Django 4.2.2 on 2023-06-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_empresa_updatedat_alter_empregado_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='feriasEntrada',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='feriasSaida',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='nome',
            field=models.CharField(max_length=52, null=True),
        ),
    ]
