# Generated by Django 4.2.2 on 2023-07-01 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_note_alter_empregado_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_company', to='api.empresa'),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='entrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='empregado',
            name='saida',
            field=models.DateField(blank=True, null=True),
        ),
    ]
