// DO NOT EDIT THIS FILE

module.exports = {
  roots: ["<rootDir>"],
  modulePaths: ["<rootDir>"],
  collectCoverageFrom: ["<rootDir>/**/*.{js,jsx,ts,tsx}", "!src/**/*.d.ts"],
  testMatch: ["<rootDir>/**/*.{spec,test}.{js,jsx,ts,tsx}"],
  testEnvironment: "node",
  transformIgnorePatterns: [
    "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs|cjs|ts|tsx)$",
  ],
  moduleFileExtensions: [
    "web.js",
    "js",
    "web.ts",
    "ts",
    "web.tsx",
    "tsx",
    "json",
    "web.jsx",
    "jsx",
    "node",
  ],
  watchPlugins: [
    "jest-watch-typeahead/filename",
    "jest-watch-typeahead/testname",
  ],
  resetMocks: true,
  rootDir: ".",
};
