# Generated by Django 4.2.2 on 2023-06-30 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_empregado_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregado',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.empresa'),
        ),
    ]
