# Generated by Django 4.2.2 on 2023-06-30 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_empregado_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.AlterField(
            model_name='empregado',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.empresa'),
        ),
    ]
