version: "3.8"
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env.development
    networks:
      - NTT-Data-VPC
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.development
    networks:
      - NTT-Data-VPC

networks:
  NTT-Data-VPC: